#############################################################################
# Makefile for building: unpac
# Generated by qmake (3.1) (Qt 6.4.1)
# Project:  unpac.pro
# Template: app
# Command: /nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/bin/qmake -o Makefile unpac.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -Wextra -fPIC -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -Wextra -fPIC -D_REENTRANT $(DEFINES)
INCPATH       = -I. -Iinclude -I/nix/store/wlgj12rfhsrm5a0mixk2fsjgzcahykzd-qtbase-6.4.1-dev/include -I/nix/store/wlgj12rfhsrm5a0mixk2fsjgzcahykzd-qtbase-6.4.1-dev/include/QtGui -I/nix/store/wlgj12rfhsrm5a0mixk2fsjgzcahykzd-qtbase-6.4.1-dev/include/QtCore -I. -I/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/linux-g++
QMAKE         = /nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/bin/qmake -install qinstall
QINSTALL_PROGRAM = /nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = unpac1.0.0
DISTDIR = /home/runner/unpac/build/unpac1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/nix/store/g6lhj0d0q8486d0vyhyfh2kn4s4l2562-qtbase-6.4.1/lib -Wl,-rpath-link,/nix/store/g6lhj0d0q8486d0vyhyfh2kn4s4l2562-qtbase-6.4.1/lib
LIBS          = $(SUBLIBS) -lfmt /nix/store/g6lhj0d0q8486d0vyhyfh2kn4s4l2562-qtbase-6.4.1/lib/libQt6Gui.so /nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/lib/libQt6Core.so /nix/store/g6lhj0d0q8486d0vyhyfh2kn4s4l2562-qtbase-6.4.1/lib/libQt6Core.so -lpthread -lGLX -lOpenGL   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = build/

####### Files

SOURCES       = src/main.cpp \
		src/util.cpp \
		src/filename.cpp \
		src/bytestream.cpp \
		src/my_file.cpp \
		src/arcv.cpp \
		src/my_endian.cpp 
OBJECTS       = build/main.o \
		build/util.o \
		build/filename.o \
		build/bytestream.o \
		build/my_file.o \
		build/arcv.o \
		build/my_endian.o
DIST          = /nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/features/spec_pre.prf \
		/nix/store/wlgj12rfhsrm5a0mixk2fsjgzcahykzd-qtbase-6.4.1-dev/mkspecs/common/unix.conf \
		/nix/store/wlgj12rfhsrm5a0mixk2fsjgzcahykzd-qtbase-6.4.1-dev/mkspecs/common/linux.conf \
		/nix/store/wlgj12rfhsrm5a0mixk2fsjgzcahykzd-qtbase-6.4.1-dev/mkspecs/common/sanitize.conf \
		/nix/store/wlgj12rfhsrm5a0mixk2fsjgzcahykzd-qtbase-6.4.1-dev/mkspecs/common/gcc-base.conf \
		/nix/store/wlgj12rfhsrm5a0mixk2fsjgzcahykzd-qtbase-6.4.1-dev/mkspecs/common/gcc-base-unix.conf \
		/nix/store/wlgj12rfhsrm5a0mixk2fsjgzcahykzd-qtbase-6.4.1-dev/mkspecs/common/g++-base.conf \
		/nix/store/wlgj12rfhsrm5a0mixk2fsjgzcahykzd-qtbase-6.4.1-dev/mkspecs/common/g++-unix.conf \
		/nix/store/wlgj12rfhsrm5a0mixk2fsjgzcahykzd-qtbase-6.4.1-dev/mkspecs/qconfig.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_3danimation.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_3danimation_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_3dcore.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_3dcore_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_3dextras.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_3dextras_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_3dinput.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_3dinput_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_3dlogic.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_3dquick.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_3dquick_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_3dquickextras.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_3dquickinput.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_3dquickrender.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_3drender.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_3drender_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_bluetooth.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_bodymovin_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_charts.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_charts_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_chartsqml.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_chartsqml_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_concurrent.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_concurrent_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_core.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_core5compat.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_core5compat_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_core_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_dbus.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_dbus_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_designer.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_designer_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_fb_support_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_gui.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_gui_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_help.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_help_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_hunspellinputmethod.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_hunspellinputmethod_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_input_support_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_kms_support_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_labsanimation.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_labsanimation_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_labsfolderlistmodel.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_labsqmlmodels.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_labsqmlmodels_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_labssettings.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_labssettings_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_labssharedimage.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_labssharedimage_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_labswavefrontmesh.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_linguist.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_linguist_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_multimedia.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_multimedia_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_multimediaquick_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_network.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_network_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_networkauth.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_networkauth_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_nfc.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_nfc_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_opengl.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_opengl_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_openglwidgets.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_pdf.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_pdf_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_pdfquick.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_pdfquick_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_pdfwidgets.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_pdfwidgets_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_positioning.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_positioning_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_positioningquick.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_printsupport.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_printsupport_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_qml.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_qml_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_qmlcore.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_qmlcore_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_qmldom_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_qmlintegration.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_qmlintegration_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_qmllocalstorage.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_qmllocalstorage_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_qmlmodels.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_qmltest.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_qmltest_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_qmlxmllistmodel.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_quick.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_quick3d.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_quick3d_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_quick3dassetutils.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_quick3dassetutils_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_quick3deffects.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_quick3deffects_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_quick3dglslparser_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_quick3dhelpers.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_quick3dhelpers_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_quick3diblbaker.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_quick3diblbaker_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_quick3dparticleeffects.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_quick3dparticleeffects_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_quick3dparticles.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_quick3dparticles_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_quick3dutils.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_quick_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_quickdialogs2.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_quickdialogs2_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_quickdialogs2utils.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_quicklayouts.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_quicklayouts_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_quickwidgets.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_scxml.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_scxml_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_scxmlqml.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_scxmlqml_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_sensors.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_sensors_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_sensorsquick.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_sensorsquick_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_serialbus.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_serialbus_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_serialport.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_serialport_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_shadertools.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_shadertools_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_spatialaudio.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_spatialaudio_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_sql.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_sql_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_statemachine.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_statemachine_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_statemachineqml.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_statemachineqml_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_svg.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_svg_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_svgwidgets.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_svgwidgets_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_testlib.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_testlib_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_tools_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_uiplugin.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_uitools.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_uitools_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_wayland_egl_client_hw_integration_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_wayland_egl_compositor_hw_integration_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_waylandclient.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_waylandclient_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_waylandcompositor.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_waylandcompositor_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_waylandglobal_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_webchannel.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_webchannel_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_webenginecore.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_webenginequick.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_webenginequick_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_webenginequickdelegatesqml.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_webenginequickdelegatesqml_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_websockets.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_websockets_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_webview.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_webview_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_webviewquick.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_webviewquick_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_widgets.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_widgets_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_wl_shell_integration_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_xml.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_xml_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/features/qt_functions.prf \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/features/qt_config.prf \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/linux-g++/qmake.conf \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/features/exclusive_builds.prf \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/features/toolchain.prf \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/features/default_pre.prf \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/features/resolve_config.prf \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/features/default_post.prf \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/features/warn_on.prf \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/features/qt.prf \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/features/resources_functions.prf \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/features/resources.prf \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/features/moc.prf \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/features/unix/opengl.prf \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/features/unix/thread.prf \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/features/qmake_use.prf \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/features/file_copies.prf \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/features/testcase_targets.prf \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/features/exceptions.prf \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/features/yacc.prf \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/features/lex.prf \
		unpac.pro include/types.h \
		include/util.h \
		include/my_endian.h \
		include/filename.h \
		include/bytestream.h \
		include/my_file.h \
		include/arcv.h src/main.cpp \
		src/util.cpp \
		src/filename.cpp \
		src/bytestream.cpp \
		src/my_file.cpp \
		src/arcv.cpp \
		src/my_endian.cpp
QMAKE_TARGET  = unpac
DESTDIR       = 
TARGET        = unpac


first: all
####### Build rules

unpac:  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET)  $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: unpac.pro /nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/linux-g++/qmake.conf /nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/features/spec_pre.prf \
		/nix/store/wlgj12rfhsrm5a0mixk2fsjgzcahykzd-qtbase-6.4.1-dev/mkspecs/common/unix.conf \
		/nix/store/wlgj12rfhsrm5a0mixk2fsjgzcahykzd-qtbase-6.4.1-dev/mkspecs/common/linux.conf \
		/nix/store/wlgj12rfhsrm5a0mixk2fsjgzcahykzd-qtbase-6.4.1-dev/mkspecs/common/sanitize.conf \
		/nix/store/wlgj12rfhsrm5a0mixk2fsjgzcahykzd-qtbase-6.4.1-dev/mkspecs/common/gcc-base.conf \
		/nix/store/wlgj12rfhsrm5a0mixk2fsjgzcahykzd-qtbase-6.4.1-dev/mkspecs/common/gcc-base-unix.conf \
		/nix/store/wlgj12rfhsrm5a0mixk2fsjgzcahykzd-qtbase-6.4.1-dev/mkspecs/common/g++-base.conf \
		/nix/store/wlgj12rfhsrm5a0mixk2fsjgzcahykzd-qtbase-6.4.1-dev/mkspecs/common/g++-unix.conf \
		/nix/store/wlgj12rfhsrm5a0mixk2fsjgzcahykzd-qtbase-6.4.1-dev/mkspecs/qconfig.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_3danimation.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_3danimation_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_3dcore.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_3dcore_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_3dextras.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_3dextras_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_3dinput.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_3dinput_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_3dlogic.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_3dquick.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_3dquick_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_3dquickextras.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_3dquickinput.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_3dquickrender.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_3drender.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_3drender_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_bluetooth.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_bodymovin_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_charts.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_charts_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_chartsqml.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_chartsqml_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_concurrent.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_concurrent_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_core.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_core5compat.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_core5compat_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_core_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_dbus.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_dbus_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_designer.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_designer_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_fb_support_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_gui.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_gui_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_help.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_help_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_hunspellinputmethod.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_hunspellinputmethod_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_input_support_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_kms_support_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_labsanimation.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_labsanimation_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_labsfolderlistmodel.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_labsqmlmodels.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_labsqmlmodels_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_labssettings.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_labssettings_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_labssharedimage.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_labssharedimage_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_labswavefrontmesh.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_linguist.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_linguist_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_multimedia.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_multimedia_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_multimediaquick_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_network.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_network_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_networkauth.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_networkauth_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_nfc.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_nfc_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_opengl.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_opengl_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_openglwidgets.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_pdf.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_pdf_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_pdfquick.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_pdfquick_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_pdfwidgets.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_pdfwidgets_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_positioning.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_positioning_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_positioningquick.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_printsupport.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_printsupport_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_qml.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_qml_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_qmlcore.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_qmlcore_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_qmldom_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_qmlintegration.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_qmlintegration_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_qmllocalstorage.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_qmllocalstorage_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_qmlmodels.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_qmltest.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_qmltest_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_qmlxmllistmodel.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_quick.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_quick3d.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_quick3d_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_quick3dassetutils.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_quick3dassetutils_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_quick3deffects.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_quick3deffects_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_quick3dglslparser_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_quick3dhelpers.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_quick3dhelpers_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_quick3diblbaker.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_quick3diblbaker_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_quick3dparticleeffects.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_quick3dparticleeffects_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_quick3dparticles.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_quick3dparticles_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_quick3dutils.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_quick_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_quickdialogs2.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_quickdialogs2_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_quickdialogs2utils.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_quicklayouts.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_quicklayouts_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_quickwidgets.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_scxml.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_scxml_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_scxmlqml.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_scxmlqml_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_sensors.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_sensors_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_sensorsquick.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_sensorsquick_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_serialbus.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_serialbus_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_serialport.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_serialport_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_shadertools.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_shadertools_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_spatialaudio.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_spatialaudio_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_sql.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_sql_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_statemachine.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_statemachine_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_statemachineqml.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_statemachineqml_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_svg.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_svg_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_svgwidgets.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_svgwidgets_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_testlib.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_testlib_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_tools_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_uiplugin.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_uitools.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_uitools_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_wayland_egl_client_hw_integration_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_wayland_egl_compositor_hw_integration_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_waylandclient.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_waylandclient_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_waylandcompositor.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_waylandcompositor_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_waylandglobal_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_webchannel.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_webchannel_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_webenginecore.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_webenginequick.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_webenginequick_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_webenginequickdelegatesqml.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_webenginequickdelegatesqml_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_websockets.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_websockets_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_webview.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_webview_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_webviewquick.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_webviewquick_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_widgets.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_widgets_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_wl_shell_integration_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_xml.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_xml_private.pri \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/features/qt_functions.prf \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/features/qt_config.prf \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/linux-g++/qmake.conf \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/features/exclusive_builds.prf \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/features/toolchain.prf \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/features/default_pre.prf \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/features/resolve_config.prf \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/features/default_post.prf \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/features/warn_on.prf \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/features/qt.prf \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/features/resources_functions.prf \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/features/resources.prf \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/features/moc.prf \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/features/unix/opengl.prf \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/features/unix/thread.prf \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/features/qmake_use.prf \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/features/file_copies.prf \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/features/testcase_targets.prf \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/features/exceptions.prf \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/features/yacc.prf \
		/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/features/lex.prf \
		unpac.pro \
		/nix/store/g6lhj0d0q8486d0vyhyfh2kn4s4l2562-qtbase-6.4.1/lib/libQt6Gui.prl \
		/nix/store/g6lhj0d0q8486d0vyhyfh2kn4s4l2562-qtbase-6.4.1/lib/libQt6Core.prl
	$(QMAKE) -o Makefile unpac.pro
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/features/spec_pre.prf:
/nix/store/wlgj12rfhsrm5a0mixk2fsjgzcahykzd-qtbase-6.4.1-dev/mkspecs/common/unix.conf:
/nix/store/wlgj12rfhsrm5a0mixk2fsjgzcahykzd-qtbase-6.4.1-dev/mkspecs/common/linux.conf:
/nix/store/wlgj12rfhsrm5a0mixk2fsjgzcahykzd-qtbase-6.4.1-dev/mkspecs/common/sanitize.conf:
/nix/store/wlgj12rfhsrm5a0mixk2fsjgzcahykzd-qtbase-6.4.1-dev/mkspecs/common/gcc-base.conf:
/nix/store/wlgj12rfhsrm5a0mixk2fsjgzcahykzd-qtbase-6.4.1-dev/mkspecs/common/gcc-base-unix.conf:
/nix/store/wlgj12rfhsrm5a0mixk2fsjgzcahykzd-qtbase-6.4.1-dev/mkspecs/common/g++-base.conf:
/nix/store/wlgj12rfhsrm5a0mixk2fsjgzcahykzd-qtbase-6.4.1-dev/mkspecs/common/g++-unix.conf:
/nix/store/wlgj12rfhsrm5a0mixk2fsjgzcahykzd-qtbase-6.4.1-dev/mkspecs/qconfig.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_3danimation.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_3danimation_private.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_3dcore.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_3dcore_private.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_3dextras.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_3dextras_private.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_3dinput.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_3dinput_private.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_3dlogic.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_3dlogic_private.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_3dquick.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_3dquick_private.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_3dquickanimation.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_3dquickextras.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_3dquickextras_private.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_3dquickinput.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_3dquickrender.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_3dquickscene2d.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_3drender.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_3drender_private.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_bluetooth.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_bluetooth_private.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_bodymovin_private.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_charts.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_charts_private.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_chartsqml.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_chartsqml_private.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_concurrent.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_concurrent_private.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_core.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_core5compat.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_core5compat_private.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_core_private.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_dbus.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_dbus_private.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_designer.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_designer_private.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_designercomponents_private.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_fb_support_private.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_gui.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_gui_private.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_help.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_help_private.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_hunspellinputmethod.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_hunspellinputmethod_private.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_input_support_private.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_kms_support_private.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_labsanimation.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_labsanimation_private.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_labsfolderlistmodel.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_labsqmlmodels.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_labsqmlmodels_private.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_labssettings.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_labssettings_private.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_labssharedimage.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_labssharedimage_private.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_labswavefrontmesh.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_linguist.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_linguist_private.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_multimedia.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_multimedia_private.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_multimediaquick_private.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_multimediawidgets.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_network.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_network_private.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_networkauth.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_networkauth_private.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_nfc.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_nfc_private.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_opengl.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_opengl_private.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_openglwidgets.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_openglwidgets_private.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_pdf.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_pdf_private.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_pdfquick.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_pdfquick_private.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_pdfwidgets.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_pdfwidgets_private.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_positioning.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_positioning_private.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_positioningquick.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_positioningquick_private.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_printsupport.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_printsupport_private.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_qml.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_qml_private.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_qmlcompiler_private.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_qmlcore.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_qmlcore_private.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_qmldebug_private.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_qmldom_private.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_qmlintegration.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_qmlintegration_private.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_qmllocalstorage.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_qmllocalstorage_private.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_qmlmodels.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_qmlmodels_private.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_qmltest.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_qmltest_private.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_qmlworkerscript.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_qmlxmllistmodel.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_quick.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_quick3d.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_quick3d_private.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_quick3dassetimport.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_quick3dassetimport_private.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_quick3dassetutils.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_quick3dassetutils_private.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_quick3deffects.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_quick3deffects_private.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_quick3dglslparser_private.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_quick3dhelpers.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_quick3dhelpers_private.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_quick3diblbaker.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_quick3diblbaker_private.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_quick3dparticleeffects.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_quick3dparticleeffects_private.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_quick3dparticles.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_quick3dparticles_private.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_quick3druntimerender.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_quick3druntimerender_private.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_quick3dutils.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_quick3dutils_private.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_quick_private.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_quickcontrols2.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_quickcontrols2impl.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_quickdialogs2.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_quickdialogs2_private.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_quickdialogs2utils.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_quicklayouts.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_quicklayouts_private.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_quickparticles_private.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_quickshapes_private.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_quicktemplates2.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_quickwidgets.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_scxml.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_scxml_private.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_scxmlqml.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_scxmlqml_private.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_sensors.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_sensors_private.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_sensorsquick.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_sensorsquick_private.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_serialbus.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_serialbus_private.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_serialport.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_serialport_private.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_shadertools.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_shadertools_private.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_spatialaudio.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_spatialaudio_private.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_sql.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_sql_private.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_statemachine.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_statemachine_private.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_statemachineqml.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_statemachineqml_private.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_svg.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_svg_private.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_svgwidgets.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_svgwidgets_private.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_testlib.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_testlib_private.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_tools_private.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_uiplugin.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_uitools.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_uitools_private.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_virtualkeyboard.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_virtualkeyboard_private.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_wayland_egl_client_hw_integration_private.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_wayland_egl_compositor_hw_integration_private.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_waylandclient.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_waylandclient_private.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_waylandcompositor.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_waylandcompositor_private.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_waylandglobal_private.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_webchannel.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_webchannel_private.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_webenginecore.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_webenginecore_private.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_webenginequick.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_webenginequick_private.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_webenginequickdelegatesqml.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_webenginequickdelegatesqml_private.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_webenginewidgets.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_websockets.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_websockets_private.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_webview.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_webview_private.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_webviewquick.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_webviewquick_private.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_widgets.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_widgets_private.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_wl_shell_integration_private.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_xml.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/modules/qt_lib_xml_private.pri:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/features/qt_functions.prf:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/features/qt_config.prf:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/linux-g++/qmake.conf:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/features/spec_post.prf:
.qmake.stash:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/features/exclusive_builds.prf:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/features/toolchain.prf:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/features/default_pre.prf:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/features/resolve_config.prf:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/features/default_post.prf:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/features/warn_on.prf:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/features/qt.prf:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/features/resources_functions.prf:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/features/resources.prf:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/features/moc.prf:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/features/unix/opengl.prf:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/features/unix/thread.prf:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/features/qmake_use.prf:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/features/file_copies.prf:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/features/testcase_targets.prf:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/features/exceptions.prf:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/features/yacc.prf:
/nix/store/1fkzzrlsrw8mppvz5cg3fr223kxgwnxx-qt-full-6.4.1/mkspecs/features/lex.prf:
unpac.pro:
/nix/store/g6lhj0d0q8486d0vyhyfh2kn4s4l2562-qtbase-6.4.1/lib/libQt6Gui.prl:
/nix/store/g6lhj0d0q8486d0vyhyfh2kn4s4l2562-qtbase-6.4.1/lib/libQt6Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile unpac.pro

qmake_all: FORCE


all: Makefile unpac

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /nix/store/wlgj12rfhsrm5a0mixk2fsjgzcahykzd-qtbase-6.4.1-dev/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents include/types.h include/util.h include/my_endian.h include/filename.h include/bytestream.h include/my_file.h include/arcv.h $(DISTDIR)/
	$(COPY_FILE) --parents src/main.cpp src/util.cpp src/filename.cpp src/bytestream.cpp src/my_file.cpp src/arcv.cpp src/my_endian.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /nix/store/wlgj12rfhsrm5a0mixk2fsjgzcahykzd-qtbase-6.4.1-dev/mkspecs/features/data/dummy.cpp
	g++ -pipe -O2 -Wall -Wextra -fPIC -dM -E -o moc_predefs.h /nix/store/wlgj12rfhsrm5a0mixk2fsjgzcahykzd-qtbase-6.4.1-dev/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean 

####### Compile

build/main.o: src/main.cpp include/bytestream.h \
		include/my_endian.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/main.o src/main.cpp

build/util.o: src/util.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/util.o src/util.cpp

build/filename.o: src/filename.cpp include/filename.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/filename.o src/filename.cpp

build/bytestream.o: src/bytestream.cpp include/bytestream.h \
		include/my_endian.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/bytestream.o src/bytestream.cpp

build/my_file.o: src/my_file.cpp include/my_file.h \
		include/bytestream.h \
		include/my_endian.h \
		include/arcv.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/my_file.o src/my_file.cpp

build/arcv.o: src/arcv.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/arcv.o src/arcv.cpp

build/my_endian.o: src/my_endian.cpp include/my_endian.h \
		include/bytestream.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/my_endian.o src/my_endian.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

.SUFFIXES:

